# Generated by Django 3.2 on 2023-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobject',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('vendor', 'vendor'), ('customer', 'customer')], default='admin', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userobject',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
